import React from "react";
import Head from "next/head";
import Button from "../components/Button/button";
import storeItems from "../data/storeItems.json";
import useSetLocalStorage from "../hooks/useSetLocalStorage";

export default function Home(): JSX.Element {
  useSetLocalStorage("store", storeItems);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="m-20">Hello world</div>
        <Button />
      </main>
    </>
  );
}
